# Generated by Django 2.2.5 on 2020-02-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytweets', '0002_hashtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HashTags',
            new_name='HashTag',
        ),
    ]

    atomic = False
